version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGOURL=mongodb://db:27017/share_energy
      - SECRET_KEY=fd646e72d5d68a572aa5ec954928c6fb0ceb2a0cab1fc399775716f8b83bf207
    volumes:
      - .:/app

  db:
    container_name: db
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
